name: Run Postman tests
on: [workflow_dispatch ]
jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Newman
        run: npm install -g newman
      - name: Check out repository code
        uses: actions/checkout@v4
      - run:  newman run Postman/Trello.postman_collection.json
